spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 215MB
  application:
    name: <mysmartinvestment>

security:
  firebase-props:
    database-url: ${FIREBASE_DATABASE}
    enable-strict-server-session: false
    enable-check-session-revoked: false
    enable-logout-everywhere: false
    session-expiry-in-days: 5
  cookie-props:
    max-age-in-minutes: 7200
    http-only: true
    secure: true
    domain: ${DOMAIN}
    path: /
  allow-credentials: true
  allowed-origins:
    - https://${DOMAIN}
    - http://localhost:8080
    - http://localhost:8080/blog/{user}
    - http://localhost:8080/blog
    - http://localhost:8080/home
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - X-Requested-With
    - X-Auth-Token
    - X-Xsrf-Token
    - X-Content-Type-Options
    - Cache-Control
    - Id-Token
  allowed-public-apis:
    - /favicon.ico
    - /home
    - /account
    - /blog
    - /login
    - /signup
    - /session
    - /css/**
    - /js/**
  exposed-headers:
    - X-Xsrf-Token